import Head from "next/head";

import { Box } from "@chakra-ui/react";

import { motion, AnimateSharedLayout } from "framer-motion";
const MotionBox = motion(Box);

export default function Home() {
  const flag = {
    hidden: { opacity: 1 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.49,
        staggerDirection: 1,
      },
    },
  };

  const color = {
    hidden: { x: "-100vw", opacity: 0 },
    show: {
      x: 0,
      opacity: 1,
      transition: { type: "spring", duration: 0.9, bounce: 0 },
    },
  };

  return (
    <Box
      as="main"
      d="flex"
      justifyContent="center"
      alignItems="center"
      h="100vh"
    >
      <Head>
        <title>Cassidoo Pride Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MotionBox
        h="100vh"
        w="100vw"
        key="flag"
        variants={flag}
        initial="hidden"
        animate="show"
      >
        <MotionBox bgColor="#E40303" h="16.6%" variants={color}></MotionBox>
        <MotionBox bgColor="#FF8C00" h="16.6%" variants={color}></MotionBox>
        <MotionBox bgColor="#FFED00" h="16.6%" variants={color}></MotionBox>
        <MotionBox bgColor="#008026" h="16.6%" variants={color}></MotionBox>
        <MotionBox bgColor="#004DFF" h="16.6%" variants={color}></MotionBox>
        <MotionBox bgColor="#750787" h="16.6%" variants={color}></MotionBox>
      </MotionBox>
    </Box>
  );
}
